### ISSUE TITLE
No recording on OSX

### ISSUE THREAD

**Issue by bertoni9** [stereolabs/zed-opencv-native#8]
Hello,
I would like to record images on a Mac. When I run the python command described in the README, I get the following error:
```
Traceback (most recent call last):
  File "zed_opencv_native.py", line 189, in <module>
    main()
  File "zed_opencv_native.py", line 163, in main
    calibration_file = download_calibration_file(serial_number)
  File "zed_opencv_native.py", line 44, in download_calibration_file
    filename = wget.download(url=url+str(serial_number), out=calibration_file)
  File "/Users/lorenzo/.virtualenvs/zed/lib/python3.7/site-packages/wget.py", line 506, in download
    (fd, tmpfile) = tempfile.mkstemp(".tmp", prefix=prefix, dir=".")
  File "/Users/lorenzo/.virtualenvs/zed/lib/python3.7/tempfile.py", line 340, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/Users/lorenzo/.virtualenvs/zed/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/zed/settings/<serialnumber>.conftzwgtefd.tmp'
```
In general, no zed folder has been created and no blue light on the camera. On the other side, the Macbook camera seems to be activated.

Thanks,
Lorenzo

**Comment by PetSven** [comment]
I am getting the same error on Windows 10.
